spring.application.name=gol

# ================================
# Configuración de la base de datos PostgreSQL
# ================================
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/gol
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# ================================
# Configuración de JPA / Hibernate
# ================================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ================================
# Cargar datos iniciales automáticamente
# ================================
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

server.port=9090
